[package]
name = "bignumbe-rs"
version = "0.1.1"
edition = "2021"
description = "Large, medium-precision numbers"
license = "GPL-3.0"

[features]
random = ["dep:rand"]
bench = []

[dependencies]
rand = {version = "0.8.5", optional = true}

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "multi"
harness = false
