[package]
name = "bignumbe-rs"
version = "0.1.6"
edition = "2021"
description = "Large, medium-precision numbers"
repository = "https://github.com/DylanBulfin/bignumbe-rs"
documentation = "https://docs.rs/bignumbe-rs/latest/bignumbe_rs"
license = "GPL-3.0"

[features]
random = ["dep:rand"]

[dependencies]
rand = {version = "0.8.5", optional = true}

[dev-dependencies]
rand = "0.8.5"
