[package]
name = "bignum"
version = "0.1.0"
edition = "2021"

[features]
random = ["dep:rand"]
bench = []

[dependencies]
rand = {version = "0.8.5", optional = true}

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "multi"
harness = false
